"""
Type stubs for InfEngine native bindings (_InfEngine.pyd).

Generated from pybind11 binding definitions in cpp/infengine/tools/pybinding/.
Provides IDE autocompletion for all C++ types exposed to Python.
"""

from __future__ import annotations

from enum import IntEnum
from typing import Any, List, Optional, Sequence, Tuple, Union, overload

import numpy as np
import numpy.typing as npt

# =============================================================================
# Module-level constants
# =============================================================================

GIZMO_X_AXIS_ID: int
GIZMO_Y_AXIS_ID: int
GIZMO_Z_AXIS_ID: int

# =============================================================================
# Enums
# =============================================================================


class LogLevel(IntEnum):
    """Engine log verbosity level."""

    Debug: int
    Info: int
    Warn: int
    Error: int
    Fatal: int


class PrimitiveType(IntEnum):
    """Primitive mesh types that can be created in a scene."""

    Cube: int
    Sphere: int
    Capsule: int
    Cylinder: int
    Plane: int


class LightType(IntEnum):
    """Types of light sources."""

    Directional: int
    Point: int
    Spot: int
    Area: int


class LightShadows(IntEnum):
    """Shadow mode for lights."""

    NoShadows: int
    Hard: int
    Soft: int


class ScenePassType(IntEnum):
    """Built-in scene render pass types."""

    DepthPrePass: int
    ShadowPass: int
    MainColor: int
    Transparent: int
    UI: int
    Custom: int


class GraphPassActionType(IntEnum):
    """Render action for a graph pass."""

    NONE: int
    DRAW_RENDERERS: int
    DRAW_SKYBOX: int
    COMPUTE: int
    CUSTOM: int
    DRAW_SHADOW_CASTERS: int


class ResourceType(IntEnum):
    """File resource types in the asset system."""

    Meta: int
    Shader: int
    Texture: int
    Mesh: int
    Material: int
    Script: int
    Audio: int
    DefaultText: int
    DefaultBinary: int


class SortingCriteria(IntEnum):
    """Sorting criteria for draw calls."""

    NONE: int
    COMMON_OPAQUE: int
    COMMON_TRANSPARENT: int
    OPTIMIZE_STATE_CHANGES: int


class VkFormat(IntEnum):
    """Vulkan image format (subset for render target creation)."""

    R8G8B8A8_UNORM: int
    R8G8B8A8_SRGB: int
    B8G8R8A8_UNORM: int
    R16G16B16A16_SFLOAT: int
    R32G32B32A32_SFLOAT: int
    R32_SFLOAT: int
    D32_SFLOAT: int
    D24_UNORM_S8_UINT: int


class VkSampleCount(IntEnum):
    """Vulkan MSAA sample count."""

    COUNT_1: int
    COUNT_2: int
    COUNT_4: int
    COUNT_8: int


# =============================================================================
# Math types
# =============================================================================


class vec2f:
    """2D float vector with swizzle-style properties and arithmetic operators."""

    x: float
    y: float
    r: float
    g: float

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, value: float) -> None: ...
    def __add__(self, other: Union[vec2f, int, float]) -> vec2f: ...
    def __radd__(self, other: Union[int, float]) -> vec2f: ...
    def __sub__(self, other: Union[vec2f, int, float]) -> vec2f: ...
    def __rsub__(self, other: Union[int, float]) -> vec2f: ...
    def __mul__(self, other: Union[vec2f, int, float]) -> vec2f: ...
    def __rmul__(self, other: Union[int, float]) -> vec2f: ...
    def __truediv__(self, other: Union[vec2f, int, float]) -> vec2f: ...
    def __rtruediv__(self, other: Union[int, float]) -> vec2f: ...
    def __iadd__(self, other: Union[vec2f, int, float]) -> vec2f: ...
    def __isub__(self, other: Union[vec2f, int, float]) -> vec2f: ...
    def __imul__(self, other: Union[int, float]) -> vec2f: ...
    def __itruediv__(self, other: Union[int, float]) -> vec2f: ...
    def __eq__(self, other: vec2f) -> bool: ...
    def __ne__(self, other: vec2f) -> bool: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def up() -> vec2f: ...
    @staticmethod
    def down() -> vec2f: ...
    @staticmethod
    def left() -> vec2f: ...
    @staticmethod
    def right() -> vec2f: ...
    @staticmethod
    def zero() -> vec2f: ...
    @staticmethod
    def one() -> vec2f: ...
    @staticmethod
    def negative_infinity() -> vec2f: ...
    @staticmethod
    def positive_infinity() -> vec2f: ...
    @staticmethod
    def cross(a: vec2f, b: vec2f) -> float: ...
    @staticmethod
    def magnitude(v: vec2f) -> float: ...
    @staticmethod
    def normalize(v: vec2f) -> vec2f: ...
    @staticmethod
    def sqr_magnitude(v: vec2f) -> float: ...
    @staticmethod
    def angle(a: vec2f, b: vec2f) -> float: ...
    @staticmethod
    def clamp_magnitude(v: vec2f, max_length: float) -> vec2f: ...
    @staticmethod
    def distance(a: vec2f, b: vec2f) -> float: ...
    @staticmethod
    def dot(a: vec2f, b: vec2f) -> float: ...
    @staticmethod
    def lerp(a: vec2f, b: vec2f, t: float) -> vec2f: ...
    @staticmethod
    def lerp_unclamped(a: vec2f, b: vec2f, t: float) -> vec2f: ...
    @staticmethod
    def max(a: vec2f, b: vec2f) -> vec2f: ...
    @staticmethod
    def min(a: vec2f, b: vec2f) -> vec2f: ...
    @staticmethod
    def move_towards(current: vec2f, target: vec2f, max_delta: float) -> vec2f: ...
    @staticmethod
    def reflect(direction: vec2f, normal: vec2f) -> vec2f: ...
    @staticmethod
    def signed_angle(a: vec2f, b: vec2f) -> float: ...
    @staticmethod
    def smooth_damp(
        current: vec2f,
        target: vec2f,
        current_velocity: vec2f,
        smooth_time: float,
        max_speed: float,
        delta_time: float,
    ) -> vec2f: ...


class vec3f:
    """3D float vector with swizzle-style properties and arithmetic operators."""

    x: float
    y: float
    z: float
    r: float
    g: float
    b: float

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, value: float) -> None: ...
    def __add__(self, other: Union[vec3f, int, float]) -> vec3f: ...
    def __radd__(self, other: Union[int, float]) -> vec3f: ...
    def __sub__(self, other: Union[vec3f, int, float]) -> vec3f: ...
    def __rsub__(self, other: Union[int, float]) -> vec3f: ...
    def __mul__(self, other: Union[vec3f, int, float]) -> vec3f: ...
    def __rmul__(self, other: Union[int, float]) -> vec3f: ...
    def __truediv__(self, other: Union[vec3f, int, float]) -> vec3f: ...
    def __rtruediv__(self, other: Union[int, float]) -> vec3f: ...
    def __iadd__(self, other: Union[vec3f, int, float]) -> vec3f: ...
    def __isub__(self, other: Union[vec3f, int, float]) -> vec3f: ...
    def __imul__(self, other: Union[int, float]) -> vec3f: ...
    def __itruediv__(self, other: Union[int, float]) -> vec3f: ...
    def __eq__(self, other: vec3f) -> bool: ...
    def __ne__(self, other: vec3f) -> bool: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def up() -> vec3f: ...
    @staticmethod
    def down() -> vec3f: ...
    @staticmethod
    def left() -> vec3f: ...
    @staticmethod
    def right() -> vec3f: ...
    @staticmethod
    def forward() -> vec3f: ...
    @staticmethod
    def back() -> vec3f: ...
    @staticmethod
    def zero() -> vec3f: ...
    @staticmethod
    def one() -> vec3f: ...
    @staticmethod
    def negative_infinity() -> vec3f: ...
    @staticmethod
    def positive_infinity() -> vec3f: ...
    @staticmethod
    def cross(a: vec3f, b: vec3f) -> vec3f: ...
    @staticmethod
    def magnitude(v: vec3f) -> float: ...
    @staticmethod
    def normalize(v: vec3f) -> vec3f: ...
    @staticmethod
    def sqr_magnitude(v: vec3f) -> float: ...
    @staticmethod
    def angle(a: vec3f, b: vec3f) -> float: ...
    @staticmethod
    def clamp_magnitude(v: vec3f, max_length: float) -> vec3f: ...
    @staticmethod
    def distance(a: vec3f, b: vec3f) -> float: ...
    @staticmethod
    def dot(a: vec3f, b: vec3f) -> float: ...
    @staticmethod
    def lerp(a: vec3f, b: vec3f, t: float) -> vec3f: ...
    @staticmethod
    def lerp_unclamped(a: vec3f, b: vec3f, t: float) -> vec3f: ...
    @staticmethod
    def max(a: vec3f, b: vec3f) -> vec3f: ...
    @staticmethod
    def min(a: vec3f, b: vec3f) -> vec3f: ...
    @staticmethod
    def ortho_normalize(v1: vec3f, v2: vec3f, v3: vec3f) -> vec3f: ...
    @staticmethod
    def project(vector: vec3f, on_normal: vec3f) -> vec3f: ...
    @staticmethod
    def project_on_plane(vector: vec3f, plane_normal: vec3f) -> vec3f: ...
    @staticmethod
    def move_towards(current: vec3f, target: vec3f, max_delta: float) -> vec3f: ...
    @staticmethod
    def reflect(direction: vec3f, normal: vec3f) -> vec3f: ...
    @staticmethod
    def rotate_towards(
        current: vec3f, target: vec3f, max_radians_delta: float, max_magnitude_delta: float
    ) -> vec3f: ...
    @staticmethod
    def slerp(a: vec3f, b: vec3f, t: float) -> vec3f: ...
    @staticmethod
    def slerp_unclamped(a: vec3f, b: vec3f, t: float) -> vec3f: ...
    @staticmethod
    def signed_angle(from_: vec3f, to: vec3f, axis: vec3f) -> float: ...
    @staticmethod
    def smooth_damp(
        current: vec3f,
        target: vec3f,
        current_velocity: vec3f,
        smooth_time: float,
        max_speed: float,
        delta_time: float,
    ) -> vec3f: ...


class vec4f:
    """4D float vector with swizzle-style properties and arithmetic operators."""

    x: float
    y: float
    z: float
    w: float
    r: float
    g: float
    b: float
    a: float

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, value: float) -> None: ...
    def __add__(self, other: Union[vec4f, int, float]) -> vec4f: ...
    def __radd__(self, other: Union[int, float]) -> vec4f: ...
    def __sub__(self, other: Union[vec4f, int, float]) -> vec4f: ...
    def __rsub__(self, other: Union[int, float]) -> vec4f: ...
    def __mul__(self, other: Union[vec4f, int, float]) -> vec4f: ...
    def __rmul__(self, other: Union[int, float]) -> vec4f: ...
    def __truediv__(self, other: Union[vec4f, int, float]) -> vec4f: ...
    def __rtruediv__(self, other: Union[int, float]) -> vec4f: ...
    def __iadd__(self, other: Union[vec4f, int, float]) -> vec4f: ...
    def __isub__(self, other: Union[vec4f, int, float]) -> vec4f: ...
    def __imul__(self, other: Union[int, float]) -> vec4f: ...
    def __itruediv__(self, other: Union[int, float]) -> vec4f: ...
    def __eq__(self, other: vec4f) -> bool: ...
    def __ne__(self, other: vec4f) -> bool: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def magnitude(v: vec4f) -> float: ...
    @staticmethod
    def normalize(v: vec4f) -> vec4f: ...
    @staticmethod
    def sqr_magnitude(v: vec4f) -> float: ...
    @staticmethod
    def distance(a: vec4f, b: vec4f) -> float: ...
    @staticmethod
    def project(a: vec4f, b: vec4f) -> vec4f: ...
    @staticmethod
    def dot(a: vec4f, b: vec4f) -> float: ...
    @staticmethod
    def lerp(a: vec4f, b: vec4f, t: float) -> vec4f: ...
    @staticmethod
    def lerp_unclamped(a: vec4f, b: vec4f, t: float) -> vec4f: ...
    @staticmethod
    def max(a: vec4f, b: vec4f) -> vec4f: ...
    @staticmethod
    def min(a: vec4f, b: vec4f) -> vec4f: ...
    @staticmethod
    def move_towards(current: vec4f, target: vec4f, max_delta: float) -> vec4f: ...
    @staticmethod
    def smooth_damp(
        current: vec4f,
        target: vec4f,
        current_velocity: vec4f,
        smooth_time: float,
        max_speed: float,
        delta_time: float,
    ) -> vec4f: ...


# =============================================================================
# Scene — Components
# =============================================================================


class Component:
    """Base class for all components attached to a GameObject."""

    @property
    def type_name(self) -> str:
        """Component type name (e.g. 'Transform', 'MeshRenderer', 'Light')."""
        ...
    @property
    def component_id(self) -> int:
        """Unique component ID."""
        ...
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...
    def serialize(self) -> str:
        """Serialize component to JSON string."""
        ...
    def deserialize(self, json_str: str) -> None:
        """Deserialize component from JSON string."""
        ...


class Transform(Component):
    """Transform component — position, rotation, scale.
    
    Follows Unity convention:
      - position / euler_angles → world space
      - local_position / local_euler_angles / local_scale → local (parent) space
    """

    # ---- World-space properties ----
    @property
    def position(self) -> vec3f:
        """Position in world space (considering parent hierarchy)."""
        ...
    @position.setter
    def position(self, value: vec3f) -> None: ...
    @property
    def euler_angles(self) -> vec3f:
        """Rotation as Euler angles (degrees) in world space."""
        ...
    @euler_angles.setter
    def euler_angles(self, value: vec3f) -> None: ...

    # ---- Local-space properties ----
    @property
    def local_position(self) -> vec3f:
        """Position in local (parent) space."""
        ...
    @local_position.setter
    def local_position(self, value: vec3f) -> None: ...
    @property
    def local_euler_angles(self) -> vec3f:
        """Rotation as Euler angles (degrees) in local space."""
        ...
    @local_euler_angles.setter
    def local_euler_angles(self, value: vec3f) -> None: ...
    @property
    def local_scale(self) -> vec3f:
        """Scale in local space."""
        ...
    @local_scale.setter
    def local_scale(self, value: vec3f) -> None: ...
    @property
    def lossy_scale(self) -> vec3f:
        """Approximate world-space scale (read-only, like Unity lossyScale)."""
        ...

    # ---- Direction vectors (world) ----
    @property
    def forward(self) -> vec3f:
        """Forward direction in world space (negative Z)."""
        ...
    @property
    def right(self) -> vec3f:
        """Right direction in world space (positive X)."""
        ...
    @property
    def up(self) -> vec3f:
        """Up direction in world space (positive Y)."""
        ...

    # ---- Direction vectors (local) ----
    @property
    def local_forward(self) -> vec3f:
        """Forward direction in local space (negative Z)."""
        ...
    @property
    def local_right(self) -> vec3f:
        """Right direction in local space (positive X)."""
        ...
    @property
    def local_up(self) -> vec3f:
        """Up direction in local space (positive Y)."""
        ...

    # ---- Quaternion rotation (Unity: transform.rotation / transform.localRotation) ----
    @property
    def rotation(self) -> Tuple[float, float, float, float]:
        """World-space rotation as quaternion (x, y, z, w)."""
        ...
    @rotation.setter
    def rotation(self, value: Tuple[float, float, float, float]) -> None: ...
    @property
    def local_rotation(self) -> Tuple[float, float, float, float]:
        """Local-space rotation as quaternion (x, y, z, w)."""
        ...
    @local_rotation.setter
    def local_rotation(self, value: Tuple[float, float, float, float]) -> None: ...

    # ---- Hierarchy (Unity: transform.parent, root, childCount, etc.) ----
    @property
    def parent(self) -> Optional[Transform]:
        """Parent Transform (None if root). Unity: transform.parent"""
        ...
    @parent.setter
    def parent(self, value: Optional[Transform]) -> None: ...
    @property
    def root(self) -> Transform:
        """Topmost Transform in the hierarchy. Unity: transform.root"""
        ...
    @property
    def child_count(self) -> int:
        """Number of children. Unity: transform.childCount"""
        ...
    def set_parent(self, parent: Optional[Transform], world_position_stays: bool = True) -> None:
        """Set parent Transform. Unity: transform.SetParent(parent, worldPositionStays)"""
        ...
    def get_child(self, index: int) -> Optional[Transform]:
        """Get child Transform by index. Unity: transform.GetChild(index)"""
        ...
    def find(self, name: str) -> Optional[Transform]:
        """Find child Transform by name (non-recursive). Unity: transform.Find(name)"""
        ...
    def detach_children(self) -> None:
        """Unparent all children. Unity: transform.DetachChildren()"""
        ...
    def is_child_of(self, parent: Transform) -> bool:
        """Is this transform a child of parent? Unity: transform.IsChildOf(parent)"""
        ...
    def get_sibling_index(self) -> int:
        """Get sibling index. Unity: transform.GetSiblingIndex()"""
        ...
    def set_sibling_index(self, index: int) -> None:
        """Set sibling index. Unity: transform.SetSiblingIndex(index)"""
        ...
    def set_as_first_sibling(self) -> None:
        """Move to first sibling. Unity: transform.SetAsFirstSibling()"""
        ...
    def set_as_last_sibling(self) -> None:
        """Move to last sibling. Unity: transform.SetAsLastSibling()"""
        ...

    # ---- Space conversion methods ----
    def transform_point(self, point: vec3f) -> vec3f:
        """Transform point from local to world space. Unity: transform.TransformPoint(point)"""
        ...
    def inverse_transform_point(self, point: vec3f) -> vec3f:
        """Transform point from world to local space. Unity: transform.InverseTransformPoint(point)"""
        ...
    def transform_direction(self, direction: vec3f) -> vec3f:
        """Transform direction from local to world (rotation only). Unity: transform.TransformDirection(dir)"""
        ...
    def inverse_transform_direction(self, direction: vec3f) -> vec3f:
        """Transform direction from world to local (rotation only). Unity: transform.InverseTransformDirection(dir)"""
        ...
    def transform_vector(self, vector: vec3f) -> vec3f:
        """Transform vector from local to world (with scale). Unity: transform.TransformVector(vec)"""
        ...
    def inverse_transform_vector(self, vector: vec3f) -> vec3f:
        """Transform vector from world to local (with scale). Unity: transform.InverseTransformVector(vec)"""
        ...

    # ---- Matrices ----
    def local_to_world_matrix(self) -> List[float]:
        """Get local-to-world transformation matrix (16 floats, column-major). Unity: transform.localToWorldMatrix"""
        ...
    def world_to_local_matrix(self) -> List[float]:
        """Get world-to-local transformation matrix (16 floats, column-major). Unity: transform.worldToLocalMatrix"""
        ...

    # ---- Methods ----
    def look_at(self, target: vec3f) -> None:
        """Rotate to face a world-space target position."""
        ...
    def translate(self, delta: vec3f) -> None:
        """Translate in world space."""
        ...
    def translate_local(self, delta: vec3f) -> None:
        """Translate in local space (relative to own axes)."""
        ...
    def rotate(self, euler: vec3f) -> None:
        """Rotate by Euler angles (degrees) in local space. Unity: transform.Rotate(euler)"""
        ...
    def rotate_around(self, point: vec3f, axis: vec3f, angle: float) -> None:
        """Rotate around a world-space point. Unity: transform.RotateAround(point, axis, angle)"""
        ...

    # ---- hasChanged ----
    @property
    def has_changed(self) -> bool:
        """Has the transform changed since last reset? Unity: transform.hasChanged"""
        ...
    @has_changed.setter
    def has_changed(self, value: bool) -> None: ...



class MeshRenderer(Component):
    """Renders a mesh with a material."""

    def has_inline_mesh(self) -> bool: ...
    def has_render_material(self) -> bool:
        """Check if a custom material is assigned."""
        ...
    @property
    def render_material(self) -> Optional[InfMaterial]:
        """The material used for rendering."""
        ...
    @render_material.setter
    def render_material(self, value: Optional[InfMaterial]) -> None: ...
    def get_effective_material(self) -> Optional[InfMaterial]:
        """Get the effective material (custom or default)."""
        ...
    @property
    def vertex_count(self) -> int:
        """Number of vertices in inline mesh (0 if using resource mesh)."""
        ...
    @property
    def index_count(self) -> int:
        """Number of indices in inline mesh (0 if using resource mesh)."""
        ...
    def get_positions(self) -> List[Tuple[float, float, float]]:
        """Get all vertex positions as (x, y, z) tuples."""
        ...
    def get_normals(self) -> List[Tuple[float, float, float]]:
        """Get all vertex normals as (x, y, z) tuples."""
        ...
    def get_uvs(self) -> List[Tuple[float, float]]:
        """Get all vertex UVs as (u, v) tuples."""
        ...
    def get_indices(self) -> List[int]:
        """Get all indices as a flat list."""
        ...
    @property
    def casts_shadows(self) -> bool:
        """Whether this renderer casts shadows."""
        ...
    @casts_shadows.setter
    def casts_shadows(self, value: bool) -> None: ...
    @property
    def receives_shadows(self) -> bool:
        """Whether this renderer receives shadows."""
        ...
    @receives_shadows.setter
    def receives_shadows(self, value: bool) -> None: ...
    def serialize(self) -> str: ...


class Light(Component):
    """Light component (Directional, Point, Spot, Area)."""

    @property
    def light_type(self) -> LightType:
        """Type of light."""
        ...
    @light_type.setter
    def light_type(self, value: LightType) -> None: ...
    @property
    def color(self) -> vec3f:
        """Light color (linear RGB)."""
        ...
    @color.setter
    def color(self, value: vec3f) -> None: ...
    @property
    def intensity(self) -> float:
        """Light intensity multiplier."""
        ...
    @intensity.setter
    def intensity(self, value: float) -> None: ...
    @property
    def range(self) -> float:
        """Light range (Point/Spot lights)."""
        ...
    @range.setter
    def range(self, value: float) -> None: ...
    @property
    def spot_angle(self) -> float:
        """Inner spot angle in degrees."""
        ...
    @spot_angle.setter
    def spot_angle(self, value: float) -> None: ...
    @property
    def outer_spot_angle(self) -> float:
        """Outer spot angle in degrees."""
        ...
    @outer_spot_angle.setter
    def outer_spot_angle(self, value: float) -> None: ...
    @property
    def shadows(self) -> LightShadows:
        """Shadow type (None, Hard, Soft)."""
        ...
    @shadows.setter
    def shadows(self, value: LightShadows) -> None: ...
    @property
    def shadow_strength(self) -> float:
        """Shadow strength (0-1)."""
        ...
    @shadow_strength.setter
    def shadow_strength(self, value: float) -> None: ...
    @property
    def shadow_bias(self) -> float:
        """Shadow depth bias."""
        ...
    @shadow_bias.setter
    def shadow_bias(self, value: float) -> None: ...
    def get_light_view_matrix(self) -> Any:
        """Get the light's view matrix for shadow mapping."""
        ...
    def get_light_projection_matrix(
        self,
        shadow_extent: float = 20.0,
        near_plane: float = 0.1,
        far_plane: float = 100.0,
    ) -> Any:
        """Get the light's projection matrix for shadow mapping."""
        ...
    def serialize(self) -> str: ...


class PyComponentProxy(Component):
    """C++ proxy wrapping a Python InfComponent instance."""

    def get_py_component(self) -> Any:
        """Get the underlying Python component."""
        ...
    def get_py_type_name(self) -> str:
        """Get the Python type name."""
        ...
    def is_valid(self) -> bool:
        """Check if this proxy holds a valid Python component."""
        ...


# =============================================================================
# Audio — AudioClip, AudioSource, AudioListener, AudioEngine
# =============================================================================


class AudioClip:
    """Loaded audio clip data (WAV). Use load_from_file() to load."""

    def __init__(self) -> None: ...
    def load_from_file(self, file_path: str) -> bool:
        """Load audio data from a WAV file. Returns True on success."""
        ...
    def unload(self) -> None:
        """Unload audio data and free memory."""
        ...
    @property
    def is_loaded(self) -> bool:
        """Whether the clip has loaded data."""
        ...
    @property
    def duration(self) -> float:
        """Duration in seconds."""
        ...
    @property
    def sample_count(self) -> int:
        """Total sample frames."""
        ...
    @property
    def sample_rate(self) -> int:
        """Sample rate in Hz."""
        ...
    @property
    def channels(self) -> int:
        """Number of channels (1=mono, 2=stereo)."""
        ...
    @property
    def file_path(self) -> str:
        """Source file path."""
        ...
    @property
    def name(self) -> str:
        """Clip name (filename without extension)."""
        ...


class AudioSource(Component):
    """Audio playback component. Attach to a GameObject to play AudioClips."""

    def play(self) -> None:
        """Start playing the assigned clip."""
        ...
    def stop(self) -> None:
        """Stop playback and reset position."""
        ...
    def pause(self) -> None:
        """Pause playback."""
        ...
    def un_pause(self) -> None:
        """Resume paused playback."""
        ...
    @property
    def is_playing(self) -> bool:
        """Whether currently playing."""
        ...
    @property
    def is_paused(self) -> bool:
        """Whether paused."""
        ...
    @property
    def clip(self) -> Optional[AudioClip]: ...
    @clip.setter
    def clip(self, value: Optional[AudioClip]) -> None: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, value: float) -> None: ...
    @property
    def pitch(self) -> float: ...
    @pitch.setter
    def pitch(self, value: float) -> None: ...
    @property
    def mute(self) -> bool: ...
    @mute.setter
    def mute(self, value: bool) -> None: ...
    @property
    def loop(self) -> bool: ...
    @loop.setter
    def loop(self, value: bool) -> None: ...
    @property
    def play_on_awake(self) -> bool: ...
    @play_on_awake.setter
    def play_on_awake(self, value: bool) -> None: ...
    @property
    def min_distance(self) -> float: ...
    @min_distance.setter
    def min_distance(self, value: float) -> None: ...
    @property
    def max_distance(self) -> float: ...
    @max_distance.setter
    def max_distance(self, value: float) -> None: ...
    @property
    def output_bus(self) -> str: ...
    @output_bus.setter
    def output_bus(self, value: str) -> None: ...
    @property
    def game_object_id(self) -> int: ...
    def serialize(self) -> str: ...
    def deserialize(self, json_str: str) -> None: ...


class AudioListener(Component):
    """Audio listener component — the 'ears' in the scene."""

    @property
    def game_object_id(self) -> int: ...
    def serialize(self) -> str: ...
    def deserialize(self, json_str: str) -> None: ...


class AudioEngine:
    """Core audio engine (singleton). Access via AudioEngine.instance()."""

    @staticmethod
    def instance() -> "AudioEngine":
        """Get the singleton AudioEngine instance."""
        ...
    def initialize(self) -> bool:
        """Initialize the audio subsystem."""
        ...
    def shutdown(self) -> None:
        """Shutdown the audio subsystem."""
        ...
    @property
    def is_initialized(self) -> bool: ...
    @property
    def master_volume(self) -> float: ...
    @master_volume.setter
    def master_volume(self, value: float) -> None: ...
    def pause_all(self) -> None:
        """Pause all audio playback."""
        ...
    def resume_all(self) -> None:
        """Resume all audio playback."""
        ...
    @property
    def is_paused(self) -> bool: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channel_count(self) -> int: ...


# =============================================================================
# Scene — GameObject, Scene, SceneManager
# =============================================================================


class GameObject:
    """A game object in the scene hierarchy with components."""

    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def active(self) -> bool: ...
    @active.setter
    def active(self, value: bool) -> None: ...
    @property
    def id(self) -> int:
        """Unique object ID."""
        ...
    @property
    def transform(self) -> Transform:
        """Get the Transform component."""
        ...
    def get_transform(self) -> Transform:
        """Get the Transform component."""
        ...
    def add_component(self, component_type: Union[str, type]) -> Optional[Component]:
        """Add a C++ component by type or type name."""
        ...
    def remove_component(self, component: Component) -> bool:
        """Remove a component instance (cannot remove Transform)."""
        ...
    def get_components(self) -> List[Component]:
        """Get all components (including Transform)."""
        ...
    def get_cpp_component(self, type_name: str) -> Optional[Component]:
        """Get a C++ component by type name (e.g., 'Transform', 'MeshRenderer', 'Light')."""
        ...
    def get_cpp_components(self, type_name: str) -> List[Component]:
        """Get all C++ components of a given type name."""
        ...
    def add_py_component(self, component_instance: Any) -> Optional[Any]:
        """Add a Python InfComponent instance to this GameObject."""
        ...
    def get_py_component(self, component_type: type) -> Optional[Any]:
        """Get a Python component of the specified type."""
        ...
    def get_py_components(self) -> List[Any]:
        """Get all Python components attached to this GameObject."""
        ...
    def remove_py_component(self, component: Any) -> bool:
        """Remove a Python component instance."""
        ...
    def get_parent(self) -> Optional[GameObject]:
        """Get the parent GameObject."""
        ...
    def set_parent(self, parent: Optional[GameObject], world_position_stays: bool = True) -> None:
        """Set the parent GameObject (None for root). world_position_stays preserves world transform."""
        ...
    def get_children(self) -> List[GameObject]:
        """Get list of child GameObjects."""
        ...
    def get_child_count(self) -> int:
        """Get the number of children."""
        ...
    def is_active_in_hierarchy(self) -> bool:
        """Check if this object and all parents are active."""
        ...
    @property
    def active_self(self) -> bool:
        """Is this object itself active? Alias for active. Unity: gameObject.activeSelf"""
        ...
    @property
    def active_in_hierarchy(self) -> bool:
        """Is this object active in the hierarchy? Unity: gameObject.activeInHierarchy"""
        ...
    @property
    def is_static(self) -> bool:
        """Static flag. Unity: gameObject.isStatic"""
        ...
    @is_static.setter
    def is_static(self, value: bool) -> None: ...
    @property
    def scene(self) -> Optional[Scene]:
        """The Scene this GameObject belongs to. Unity: gameObject.scene"""
        ...
    def get_child(self, index: int) -> Optional[GameObject]:
        """Get child by index. Unity: transform.GetChild(index).gameObject"""
        ...
    def find_child(self, name: str) -> Optional[GameObject]:
        """Find direct child by name (non-recursive)."""
        ...
    def find_descendant(self, name: str) -> Optional[GameObject]:
        """Find descendant by name (recursive depth-first search)."""
        ...
    @property
    def tag(self) -> str:
        """Tag string for this GameObject."""
        ...
    @tag.setter
    def tag(self, value: str) -> None: ...
    @property
    def layer(self) -> int:
        """Layer index (0-31) for this GameObject."""
        ...
    @layer.setter
    def layer(self, value: int) -> None: ...
    def compare_tag(self, tag: str) -> bool:
        """Returns True if this GameObject's tag matches the given tag."""
        ...
    def serialize(self) -> str:
        """Serialize GameObject to JSON string."""
        ...
    def deserialize(self, json_str: str) -> None:
        """Deserialize GameObject from JSON string."""
        ...


class PendingPyComponent:
    """Data for a Python component awaiting restoration after deserialization."""

    @property
    def game_object_id(self) -> int: ...
    @property
    def type_name(self) -> str: ...
    @property
    def script_guid(self) -> str: ...
    @property
    def fields_json(self) -> str: ...
    @property
    def enabled(self) -> bool: ...


class Scene:
    """A scene containing GameObjects."""

    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    def create_game_object(self, name: str = "GameObject") -> GameObject:
        """Create a new empty GameObject in this scene."""
        ...
    def create_primitive(self, type: PrimitiveType, name: str = "") -> GameObject:
        """Create a primitive GameObject (Cube, Sphere, Capsule, Cylinder, Plane)."""
        ...
    def get_root_objects(self) -> List[GameObject]:
        """Get all root-level GameObjects."""
        ...
    def get_all_objects(self) -> List[GameObject]:
        """Get all GameObjects in the scene."""
        ...
    def find(self, name: str) -> Optional[GameObject]:
        """Find a GameObject by name."""
        ...
    def find_by_id(self, id: int) -> Optional[GameObject]:
        """Find a GameObject by ID."""
        ...
    def find_with_tag(self, tag: str) -> Optional[GameObject]:
        """Find the first GameObject with a given tag."""
        ...
    def find_game_objects_with_tag(self, tag: str) -> List[GameObject]:
        """Find all GameObjects with a given tag."""
        ...
    def find_game_objects_in_layer(self, layer: int) -> List[GameObject]:
        """Find all GameObjects in a given layer."""
        ...
    def destroy_game_object(self, game_object: GameObject) -> None:
        """Destroy a GameObject (removed at end of frame)."""
        ...
    def process_pending_destroys(self) -> None:
        """Process pending GameObject destroys."""
        ...
    def is_playing(self) -> bool:
        """Check if the scene is in play mode."""
        ...
    def start(self) -> None:
        """Trigger Awake+Start on all components (idempotent — skipped if already started)."""
        ...
    def serialize(self) -> str:
        """Serialize scene to JSON string."""
        ...
    def deserialize(self, json_str: str) -> None:
        """Deserialize scene from JSON string."""
        ...
    def save_to_file(self, path: str) -> None:
        """Save scene to a JSON file."""
        ...
    def load_from_file(self, path: str) -> None:
        """Load scene from a JSON file."""
        ...
    def has_pending_py_components(self) -> bool:
        """Check if there are pending Python components to restore."""
        ...
    def take_pending_py_components(self) -> List[PendingPyComponent]:
        """Get and clear pending Python components for restoration."""
        ...


class SceneManager:
    """Singleton scene manager controlling scene lifecycle and play mode."""

    @staticmethod
    def instance() -> SceneManager:
        """Get the singleton SceneManager instance."""
        ...
    def create_scene(self, name: str) -> Scene:
        """Create a new empty scene."""
        ...
    def get_active_scene(self) -> Optional[Scene]:
        """Get the currently active scene."""
        ...
    def set_active_scene(self, scene: Scene) -> None:
        """Set the active scene."""
        ...
    def get_scene(self, name: str) -> Optional[Scene]:
        """Get a scene by name."""
        ...
    def is_playing(self) -> bool:
        """Check if in play mode."""
        ...
    def play(self) -> None:
        """Enter play mode."""
        ...
    def stop(self) -> None:
        """Stop play mode."""
        ...
    def pause(self) -> None:
        """Pause play mode."""
        ...
    def is_paused(self) -> bool:
        """Check if paused."""
        ...
    def step(self, delta_time: float = 0.016) -> None:
        """Execute one frame while paused (FixedUpdate + Update + LateUpdate + EndFrame). No-op if not paused."""
        ...
    def dont_destroy_on_load(self, game_object: GameObject) -> None:
        """Mark a root GameObject so it survives scene switches. Unity: DontDestroyOnLoad()"""
        ...


# =============================================================================
# Resources
# =============================================================================


class ResourceMeta:
    """Resource metadata (GUID, name, type, custom key-value data)."""

    def get_resource_name(self) -> str:
        """Get resource filename without extension."""
        ...
    def get_hash_code(self) -> int:
        """Get internal hash code."""
        ...
    def get_guid(self) -> str:
        """Get stable GUID for this resource."""
        ...
    def get_resource_type(self) -> ResourceType:
        """Get the resource type."""
        ...
    def has_key(self, key: str) -> bool:
        """Check if metadata has a specific key."""
        ...
    def get_string(self, key: str) -> str:
        """Get a string metadata value."""
        ...
    def get_int(self, key: str) -> int:
        """Get an integer metadata value."""
        ...
    def get_float(self, key: str) -> float:
        """Get a float metadata value."""
        ...


class TextureData:
    """Raw texture pixel data loaded from file or created programmatically."""

    @property
    def width(self) -> int:
        """Texture width in pixels."""
        ...
    @property
    def height(self) -> int:
        """Texture height in pixels."""
        ...
    @property
    def channels(self) -> int:
        """Number of color channels (always 4 for RGBA)."""
        ...
    @property
    def name(self) -> str:
        """Texture name/identifier."""
        ...
    @property
    def source_path(self) -> str:
        """Original file path."""
        ...
    def is_valid(self) -> bool:
        """Check if texture data is valid."""
        ...
    def get_size_bytes(self) -> int:
        """Get total size in bytes."""
        ...
    def get_pixels(self) -> bytes:
        """Get raw pixel data as bytes (RGBA format)."""
        ...
    def get_pixels_list(self) -> List[int]:
        """Get raw pixel data as list of unsigned char (for upload_texture_for_imgui)."""
        ...


class TextureLoader:
    """Static methods for loading textures."""

    @staticmethod
    def load_from_file(file_path: str, name: str = "") -> TextureData:
        """Load texture from file."""
        ...
    @staticmethod
    def load_from_memory(data: bytes, name: str = "") -> TextureData:
        """Load texture from memory buffer."""
        ...
    @staticmethod
    def create_solid_color(
        width: int, height: int, r: int, g: int, b: int, a: int, name: str = "solid_color"
    ) -> TextureData:
        """Create a solid color texture."""
        ...
    @staticmethod
    def create_checkerboard(
        width: int, height: int, checker_size: int = 8, name: str = "checkerboard"
    ) -> TextureData:
        """Create a checkerboard texture."""
        ...


class FileManager:
    """Resource file manager — register, load, unload, move, delete."""

    def register_resource(self, file_path: str, type: ResourceType) -> int:
        """Register a resource file and get its UID."""
        ...
    def load_resource(self, uid: int) -> None:
        """Load a resource by its UID."""
        ...
    def unload_resource(self, uid: int) -> None:
        """Unload a resource by its UID."""
        ...
    def move_resource(self, old_path: str, new_path: str) -> None:
        """Move/rename a resource file."""
        ...
    def delete_resource(self, file_path: str) -> None:
        """Delete a resource file."""
        ...
    def modify_resource(self, file_path: str) -> None:
        """Notify that a resource has been modified."""
        ...
    def get_resource_type(self, file_path: str) -> ResourceType:
        """Get the ResourceType for a file."""
        ...
    def get_meta_by_guid(self, guid: str) -> Optional[ResourceMeta]:
        """Get resource metadata by GUID."""
        ...
    def get_meta_by_path(self, file_path: str) -> Optional[ResourceMeta]:
        """Get resource metadata by file path."""
        ...
    def get_all_resource_guids(self) -> List[str]:
        """Get all registered resource GUIDs."""
        ...


class InfMaterial:
    """Material definition with shader and property bindings."""

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str) -> None: ...
    @overload
    def __init__(self, name: str, vert_shader_path: str, frag_shader_path: str) -> None: ...
    @property
    def name(self) -> str:
        """Material name."""
        ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def guid(self) -> str:
        """Material GUID."""
        ...
    @guid.setter
    def guid(self, value: str) -> None: ...
    @property
    def file_path(self) -> str:
        """File path for saving."""
        ...
    @file_path.setter
    def file_path(self, value: str) -> None: ...
    @property
    def is_builtin(self) -> bool:
        """Whether this is a built-in material."""
        ...
    @is_builtin.setter
    def is_builtin(self, value: bool) -> None: ...
    @property
    def vertex_shader_path(self) -> str:
        """Path to the vertex shader file."""
        ...
    @vertex_shader_path.setter
    def vertex_shader_path(self, value: str) -> None: ...
    @property
    def fragment_shader_path(self) -> str:
        """Path to the fragment shader file."""
        ...
    @fragment_shader_path.setter
    def fragment_shader_path(self, value: str) -> None: ...
    def set_shaders(self, vert_path: str, frag_path: str) -> None:
        """Set both vertex and fragment shader paths."""
        ...
    def get_render_queue(self) -> int:
        """Get the render queue value."""
        ...
    def set_render_queue(self, queue: int) -> None:
        """Set the render queue value."""
        ...
    def save(self) -> None:
        """Save material to its file path."""
        ...
    def save_to(self, path: str) -> None:
        """Save material to specified path."""
        ...
    def set_float(self, name: str, value: float) -> None:
        """Set a float property."""
        ...
    def set_vector2(self, name: str, value: Union[Tuple[float, float], Sequence[float]]) -> None:
        """Set a vec2 property."""
        ...
    def set_vector3(
        self, name: str, value: Union[Tuple[float, float, float], Sequence[float]]
    ) -> None:
        """Set a vec3 property."""
        ...
    def set_vector4(
        self, name: str, value: Union[Tuple[float, float, float, float], Sequence[float]]
    ) -> None:
        """Set a vec4 property."""
        ...
    def set_color(
        self, name: str, color: Union[Tuple[float, float, float, float], Sequence[float]]
    ) -> None:
        """Set a color property (vec4)."""
        ...
    def set_int(self, name: str, value: int) -> None:
        """Set an int property."""
        ...
    def set_matrix(self, name: str, value: Any) -> None:
        """Set a mat4 property."""
        ...
    def set_texture(self, name: str, texture_path: str) -> None:
        """Set a texture property."""
        ...
    def has_property(self, name: str) -> bool:
        """Check if material has a property."""
        ...
    def get_property(self, name: str) -> Optional[Any]:
        """Get a property value by name."""
        ...
    def get_all_properties(self) -> dict:
        """Get all properties as a dictionary."""
        ...
    def is_pipeline_dirty(self) -> bool:
        """Check if pipeline needs recreation."""
        ...
    def clear_pipeline_dirty(self) -> None:
        """Clear the pipeline dirty flag."""
        ...
    def get_pipeline_hash(self) -> int:
        """Get a hash of the pipeline configuration."""
        ...
    def serialize(self) -> str:
        """Serialize material to JSON string."""
        ...
    def deserialize(self, json_str: str) -> None:
        """Deserialize material from JSON string."""
        ...
    @staticmethod
    def create_default_lit() -> InfMaterial:
        """Create the default lit opaque material (built-in)."""
        ...
    @staticmethod
    def create_default_unlit() -> InfMaterial:
        """Create a default unlit opaque material."""
        ...


class MaterialManager:
    """Singleton material registry."""

    @staticmethod
    def instance() -> MaterialManager:
        """Get the MaterialManager singleton."""
        ...
    def initialize(self) -> None: ...
    def shutdown(self) -> None: ...
    def get_default_material(self) -> InfMaterial: ...
    def get_error_material(self) -> InfMaterial:
        """Get the error material (purple-black checkerboard)."""
        ...
    def register_material(self, name: str, material: InfMaterial) -> None:
        """Register a material by name."""
        ...
    def get_material(self, name: str) -> Optional[InfMaterial]:
        """Get a material by name."""
        ...
    def has_material(self, name: str) -> bool:
        """Check if a material is registered."""
        ...
    def load_material(self, file_path: str) -> Optional[InfMaterial]:
        """Load a material from a .mat file."""
        ...
    def load_default_material_from_file(self, mat_file_path: str) -> Optional[InfMaterial]:
        """Load default material from a .mat file."""
        ...


class AssetDatabase:
    """GUID-based asset tracking database."""

    def __init__(self) -> None: ...
    def initialize(self, project_root: str) -> None:
        """Initialize asset database with project root."""
        ...
    def refresh(self) -> None:
        """Refresh assets by scanning Assets folder."""
        ...
    def import_asset(self, path: str) -> None:
        """Import a single asset."""
        ...
    def delete_asset(self, path: str) -> None:
        """Delete asset and its meta."""
        ...
    def move_asset(self, old_path: str, new_path: str) -> None:
        """Move/rename asset preserving GUID."""
        ...
    def on_asset_created(self, path: str) -> None: ...
    def on_asset_modified(self, path: str) -> None: ...
    def on_asset_deleted(self, path: str) -> None: ...
    def on_asset_moved(self, old_path: str, new_path: str) -> None: ...
    def contains_guid(self, guid: str) -> bool: ...
    def contains_path(self, path: str) -> bool: ...
    def get_guid_from_path(self, path: str) -> str: ...
    def get_path_from_guid(self, guid: str) -> str: ...
    def get_meta_by_guid(self, guid: str) -> Optional[ResourceMeta]: ...
    def get_meta_by_path(self, path: str) -> Optional[ResourceMeta]: ...
    def get_all_guids(self) -> List[str]: ...
    def is_asset_path(self, path: str) -> bool: ...
    @property
    def project_root(self) -> str: ...
    @property
    def assets_root(self) -> str: ...


# =============================================================================
# Render Pipeline
# =============================================================================


class DrawingSettings:
    """Settings controlling how renderers are drawn."""

    sorting_criteria: SortingCriteria
    override_material_index: int

    def __init__(self) -> None: ...


class FilteringSettings:
    """Settings controlling which renderers pass the filter."""

    render_queue_min: int
    render_queue_max: int
    layer_mask: int

    def __init__(self) -> None: ...
    @staticmethod
    def opaque() -> FilteringSettings:
        """Create settings for opaque objects (queue 0-2500)."""
        ...
    @staticmethod
    def transparent() -> FilteringSettings:
        """Create settings for transparent objects (queue 2501-5000)."""
        ...


class CullingResults:
    """Results of camera frustum culling."""

    @property
    def visible_object_count(self) -> int: ...
    @property
    def visible_light_count(self) -> int: ...


class CameraProjection:
    """Camera projection mode enum."""

    Perspective: CameraProjection
    Orthographic: CameraProjection

    @property
    def value(self) -> int: ...


class CameraClearFlags:
    """Camera clear flags enum (Unity URP-style)."""

    Skybox: CameraClearFlags
    SolidColor: CameraClearFlags
    DepthOnly: CameraClearFlags
    DontClear: CameraClearFlags

    @property
    def value(self) -> int: ...


class Camera:
    """Camera component with Unity-like API."""

    # Projection
    @property
    def projection_mode(self) -> CameraProjection: ...
    @projection_mode.setter
    def projection_mode(self, value: CameraProjection) -> None: ...

    @property
    def field_of_view(self) -> float: ...
    @field_of_view.setter
    def field_of_view(self, value: float) -> None: ...

    @property
    def aspect_ratio(self) -> float: ...
    @aspect_ratio.setter
    def aspect_ratio(self, value: float) -> None: ...

    @property
    def orthographic_size(self) -> float: ...
    @orthographic_size.setter
    def orthographic_size(self, value: float) -> None: ...

    @property
    def near_clip(self) -> float: ...
    @near_clip.setter
    def near_clip(self, value: float) -> None: ...

    @property
    def far_clip(self) -> float: ...
    @far_clip.setter
    def far_clip(self, value: float) -> None: ...

    # Multi-camera
    @property
    def depth(self) -> float: ...
    @depth.setter
    def depth(self, value: float) -> None: ...

    @property
    def culling_mask(self) -> int: ...
    @culling_mask.setter
    def culling_mask(self, value: int) -> None: ...

    # Phase 1: Clear flags & background color
    @property
    def clear_flags(self) -> CameraClearFlags: ...
    @clear_flags.setter
    def clear_flags(self, value: CameraClearFlags) -> None: ...

    @property
    def background_color(self) -> tuple[float, float, float, float]: ...
    @background_color.setter
    def background_color(self, value: tuple[float, float, float, float]) -> None: ...

    # Phase 0: Screen dimensions (read-only, set by renderer)
    @property
    def pixel_width(self) -> int: ...
    @property
    def pixel_height(self) -> int: ...

    # Phase 0: Coordinate conversion
    def screen_to_world_point(self, x: float, y: float, depth: float = 0.0) -> tuple[float, float, float]:
        """Convert screen coordinates (x, y) + depth [0..1] to world position."""
        ...

    def world_to_screen_point(self, x: float, y: float, z: float) -> tuple[float, float]:
        """Convert world position to screen coordinates (x, y)."""
        ...

    def serialize(self) -> str: ...
    def deserialize(self, json_str: str) -> bool: ...


class ScriptableRenderContext:
    """Context for executing render commands in a custom pipeline."""

    def setup_camera_properties(self, camera: Camera) -> None:
        """Set camera VP matrices for rendering."""
        ...
    def cull(self, camera: Camera) -> CullingResults:
        """Cull scene objects, return CullingResults."""
        ...
    def apply_graph(self, description: RenderGraphDescription) -> None:
        """Apply a Python-defined RenderGraph topology."""
        ...
    def submit_culling(self, culling: CullingResults) -> None:
        """Submit all culling results as full draw calls."""
        ...
    def get_camera_target(self, camera: Camera) -> None:
        """Get a handle representing the final camera render target."""
        ...
    def set_global_texture(self, name: str, handle: RenderTargetHandle) -> None:
        """Set a global texture shader parameter."""
        ...
    def set_global_float(self, name: str, value: float) -> None:
        """Set a global float shader parameter."""
        ...
    def set_global_vector(
        self, name: str, x: float, y: float, z: float, w: float
    ) -> None:
        """Set a global vec4 shader parameter."""
        ...


class RenderPipelineCallback:
    """Abstract base for custom Python render pipelines (override render())."""

    def __init__(self) -> None: ...
    def render(self, context: ScriptableRenderContext, cameras: List[Camera]) -> None:
        """Called once per frame to define rendering pass sequence."""
        ...
    def dispose(self) -> None:
        """Called when the pipeline is being replaced."""
        ...


# =============================================================================
# Render Graph
# =============================================================================


class ScenePassConfig:
    """Configuration for a single render pass."""

    name: str
    type: ScenePassType
    enabled: bool

    clear_color: bool
    clear_depth: bool
    clear_depth_value: float
    has_own_render_target: bool
    enable_readback: bool
    input_passes: List[str]

    def __init__(self) -> None: ...
    def set_clear_color_value(
        self, r: float, g: float, b: float, a: float = 1.0
    ) -> None:
        """Set the clear color value."""
        ...
    def get_clear_color_value(self) -> Tuple[float, float, float, float]: ...


class GraphTextureDesc:
    """Description of a texture resource in the Python-defined graph."""

    name: str
    format: int
    is_backbuffer: bool
    is_depth: bool

    def __init__(self) -> None: ...


class GraphPassDesc:
    """Description of a single render pass in the Python-defined graph."""

    name: str
    read_textures: List[str]
    write_colors: List[Tuple[int, str]]
    write_depth: str
    clear_color: bool
    clear_depth: bool
    clear_color_r: float
    clear_color_g: float
    clear_color_b: float
    clear_color_a: float
    clear_depth_value: float
    action: GraphPassActionType
    queue_min: int
    queue_max: int
    sort_mode: str
    input_bindings: List[Tuple[str, str]]

    def __init__(self) -> None: ...


class RenderGraphDescription:
    """Complete render graph topology defined by Python."""

    name: str
    textures: List[GraphTextureDesc]
    passes: List[GraphPassDesc]
    output_texture: str

    def __init__(self) -> None: ...


class SceneRenderGraph:
    """The active scene render graph — configure passes, readback pixels."""

    def remove_pass(self, name: str) -> None:
        """Remove a pass by name."""
        ...
    def set_pass_enabled(self, name: str, enabled: bool) -> None:
        """Enable/disable a pass."""
        ...
    def clear_passes(self) -> None:
        """Clear all passes."""
        ...
    def mark_dirty(self) -> None:
        """Force rebuild of the render graph on next frame."""
        ...
    def apply_python_graph(self, description: RenderGraphDescription) -> None:
        """Apply a Python-defined render graph topology."""
        ...
    def has_python_graph(self) -> bool:
        """Check if a Python graph topology has been applied."""
        ...
    def get_readable_pass_names(self) -> List[str]:
        """Get pass names that have readback enabled."""
        ...
    def get_pass_count(self) -> int:
        """Get number of configured passes."""
        ...
    def get_debug_string(self) -> str:
        """Get debug visualization of the render graph."""
        ...
    def get_pass_output_size(self, pass_name: str) -> Tuple[int, int]:
        """Get pass output dimensions as (width, height)."""
        ...
    def get_pass_texture_id(self, pass_name: str) -> int:
        """Get pass output texture ID for ImGui display."""
        ...
    def read_pass_color_pixels(self, pass_name: str) -> Optional[npt.NDArray[np.uint8]]:
        """Read color pixels as NumPy array (height, width, 4) RGBA uint8."""
        ...
    def read_pass_depth_pixels(self, pass_name: str) -> Optional[npt.NDArray[np.float32]]:
        """Read depth pixels as NumPy array (height, width) float32."""
        ...


# =============================================================================
# GUI (ImGui)
# =============================================================================


class InfGUIContext:
    """ImGui context for building editor panels and tool windows."""

    # Text & labels
    def label(self, text: str) -> None: ...

    # Buttons
    def button(self, label: str, on_click: object = None, width: float = 0.0, height: float = 0.0) -> None: ...
    def radio_button(self, label: str, active: bool) -> bool: ...
    def selectable(
        self,
        label: str,
        selected: bool = False,
        flags: int = 0,
        width: float = 0.0,
        height: float = 0.0,
    ) -> bool: ...

    # Input widgets
    def checkbox(self, label: str, value: bool) -> bool: ...
    def int_slider(self, label: str, value: int, min: int, max: int) -> int: ...
    def float_slider(
        self, label: str, value: float, min: float, max: float
    ) -> float: ...
    def drag_int(
        self, label: str, value: int, speed: float, min: int, max: int
    ) -> int: ...
    def drag_float(
        self, label: str, value: float, speed: float, min: float, max: float
    ) -> float: ...
    def text_input(
        self, label: str, value: str, buffer_size: int
    ) -> str: ...
    def text_area(self, label: str, text: str) -> str: ...
    def input_text_with_hint(
        self, label: str, hint: str, text: str
    ) -> str: ...
    def input_int(
        self,
        label: str,
        value: int,
        step: int = 1,
        step_fast: int = 100,
        flags: int = 0,
    ) -> int: ...
    def input_float(
        self,
        label: str,
        value: float,
        step: float = 0.0,
        step_fast: float = 0.0,
        flags: int = 0,
    ) -> float: ...
    def color_edit(self, label: str, color: Any) -> Any: ...
    def vector2(
        self, label: str, x: float, y: float
    ) -> Tuple[float, float]: ...
    def vector3(
        self, label: str, x: float, y: float, z: float
    ) -> Tuple[float, float, float]: ...
    def vector4(
        self, label: str, x: float, y: float, z: float, w: float
    ) -> Tuple[float, float, float, float]: ...
    def combo(
        self,
        label: str,
        current_item: int,
        items: List[str],
        popup_max_height_in_items: int = -1,
    ) -> int: ...
    def list_box(
        self,
        label: str,
        current_item: int,
        items: List[str],
        height_in_items: int = -1,
    ) -> int: ...
    def progress_bar(self, fraction: float) -> None: ...

    # Layout
    def begin_group(self, name: str = "") -> None: ...
    def end_group(self) -> None: ...
    def same_line(
        self, offset_from_start_x: float = 0.0, spacing: float = -1.0
    ) -> None: ...
    def separator(self) -> None: ...
    def spacing(self) -> None: ...
    def dummy(self, width: float, height: float) -> None: ...
    def new_line(self) -> None: ...

    # Tree
    def tree_node(self, label: str) -> bool: ...
    def tree_node_ex(self, label: str, flags: int) -> bool: ...
    def tree_pop(self) -> None: ...
    def set_next_item_open(self, is_open: bool, cond: int = 0) -> None: ...
    def set_next_item_allow_overlap(self) -> None: ...
    def collapsing_header(self, label: str) -> bool: ...
    def is_item_clicked(self, mouse_button: int = 0) -> bool: ...

    # Tabs
    def begin_tab_bar(self, id: str) -> bool: ...
    def end_tab_bar(self) -> None: ...
    def begin_tab_item(self, label: str) -> bool: ...
    def end_tab_item(self) -> None: ...

    # Menu
    def begin_main_menu_bar(self) -> bool: ...
    def end_main_menu_bar(self) -> None: ...
    def begin_menu(self, label: str, enabled: bool = True) -> bool: ...
    def end_menu(self) -> None: ...
    def menu_item(self, label: str) -> bool: ...

    # Child windows
    def begin_child(self, id: str, width: float = 0, height: float = 0) -> bool: ...
    def end_child(self) -> None: ...

    # Popups
    def open_popup(self, id: str) -> None: ...
    def begin_popup(self, id: str) -> bool: ...
    def begin_popup_modal(self, title: str, flags: int = 0) -> bool:
        """Open a modal popup. Returns true while open. Must call end_popup() when true."""
        ...
    def begin_popup_context_item(
        self, id: str = "", mouse_button: int = 1
    ) -> bool: ...
    def begin_popup_context_window(
        self, id: str = "", mouse_button: int = 1
    ) -> bool: ...
    def end_popup(self) -> None: ...

    # Tooltips
    def begin_tooltip(self) -> None: ...
    def end_tooltip(self) -> None: ...
    def set_tooltip(self, text: str) -> None: ...

    # Images
    def image(
        self,
        texture_id: int,
        width: float,
        height: float,
        uv0_x: float = 0.0,
        uv0_y: float = 0.0,
        uv1_x: float = 1.0,
        uv1_y: float = 1.0,
    ) -> None: ...
    def image_button(
        self,
        id: str,
        texture_id: int,
        width: float,
        height: float,
        uv0_x: float = 0.0,
        uv0_y: float = 0.0,
        uv1_x: float = 1.0,
        uv1_y: float = 1.0,
    ) -> bool: ...

    # Tables
    def begin_table(self, id: str, columns: int) -> bool: ...
    def end_table(self) -> None: ...
    def table_setup_column(self, label: str) -> None: ...
    def table_headers_row(self) -> None: ...
    def table_next_row(self) -> None: ...
    def table_set_column_index(self, column: int) -> None: ...
    def table_next_column(self) -> None: ...
    def checkbox_flags(self, label: str, flags: int, flag_value: int) -> int: ...

    # Size & position
    def set_next_item_width(self, width: float) -> None: ...
    def set_next_window_size(self, width: float, height: float, cond: int = ...) -> None: ...
    def set_next_window_pos(self, x: float, y: float, cond: int = ..., pivot_x: float = ..., pivot_y: float = ...) -> None: ...
    def set_next_window_focus(self) -> None: ...

    # Windows
    def begin_window(self, name: str, *args: Any) -> bool: ...
    def begin_window_closable(
        self, name: str, is_open: bool = True, flags: int = 0
    ) -> Tuple[bool, bool]:
        """Returns (is_visible, is_open)."""
        ...
    def end_window(self) -> None: ...

    # Layout queries
    def get_content_region_avail_width(self) -> float: ...
    def get_content_region_avail_height(self) -> float: ...
    def get_cursor_pos_x(self) -> float: ...
    def get_cursor_pos_y(self) -> float: ...
    def set_cursor_pos_x(self, x: float) -> None: ...
    def set_cursor_pos_y(self, y: float) -> None: ...
    def get_window_pos_x(self) -> float: ...
    def get_window_pos_y(self) -> float: ...
    def get_item_rect_min_x(self) -> float: ...
    def get_item_rect_min_y(self) -> float: ...
    def get_item_rect_max_x(self) -> float: ...
    def get_item_rect_max_y(self) -> float: ...

    # Interaction
    def invisible_button(self, id: str, width: float, height: float) -> bool: ...
    def is_item_active(self) -> bool: ...
    def is_item_hovered(self) -> bool: ...
    def set_keyboard_focus_here(self, offset: int = 0) -> None: ...
    def is_item_deactivated(self) -> bool: ...
    def is_item_deactivated_after_edit(self) -> bool: ...
    def get_mouse_drag_delta_y(self, button: int = 0) -> float: ...
    def reset_mouse_drag_delta(self, button: int = 0) -> None: ...

    # ID stack
    def push_id(self, id: int) -> None: ...
    def push_id_str(self, id: str) -> None: ...
    def pop_id(self) -> None: ...

    # Style
    def push_style_color(
        self, idx: int, r: float, g: float, b: float, a: float
    ) -> None: ...
    def pop_style_color(self, count: int = 1) -> None: ...
    def begin_disabled(self, disabled: bool = True) -> None: ...
    def end_disabled(self) -> None: ...

    # Drag and Drop
    def begin_drag_drop_source(self, flags: int = 0) -> bool: ...
    def set_drag_drop_payload(self, type: str, data: int) -> None: ...
    def set_drag_drop_payload_str(self, type: str, data: str) -> None: ...
    def end_drag_drop_source(self) -> None: ...
    def begin_drag_drop_target(self) -> bool: ...
    def accept_drag_drop_payload(self, type: str) -> Optional[Union[int, str]]: ...
    def end_drag_drop_target(self) -> None: ...

    # Mouse cursor
    def set_mouse_cursor(self, cursor_type: int) -> None: ...

    # Mouse input
    def is_mouse_button_down(self, button: int) -> bool: ...
    def is_mouse_button_clicked(self, button: int) -> bool: ...
    def is_mouse_double_clicked(self, button: int = 0) -> bool: ...
    def is_mouse_dragging(
        self, button: int, lock_threshold: float = -1.0
    ) -> bool: ...
    def get_mouse_drag_delta_x(self, button: int = 0) -> float: ...
    def get_mouse_pos_x(self) -> float: ...
    def get_mouse_pos_y(self) -> float: ...
    def get_mouse_wheel_delta(self) -> float: ...

    # Display / viewport bounds
    def get_main_viewport_bounds(self) -> Tuple[float, float, float, float]: ...
    def get_display_bounds(self) -> Tuple[float, float, float, float]: ...
    def get_global_mouse_pos_x(self) -> float: ...
    def get_global_mouse_pos_y(self) -> float: ...

    # Clipboard
    def set_clipboard_text(self, text: str) -> None: ...
    def get_clipboard_text(self) -> str: ...

    # Multiline text input
    def input_text_multiline(self, label: str, text: str, buffer_size: int = 4096, width: float = ..., height: float = ..., flags: int = ...) -> str: ...
    def draw_rect(self, min_x: float, min_y: float, max_x: float, max_y: float, r: float, g: float, b: float, a: float, thickness: float = 1.0, rounding: float = 0.0) -> None: ...
    def draw_filled_rect(self, min_x: float, min_y: float, max_x: float, max_y: float, r: float, g: float, b: float, a: float, rounding: float = 0.0) -> None: ...
    def draw_image_rect(self, texture_id: int, min_x: float, min_y: float, max_x: float, max_y: float, uv0_x: float = 0.0, uv0_y: float = 0.0, uv1_x: float = 1.0, uv1_y: float = 1.0, tint_r: float = 1.0, tint_g: float = 1.0, tint_b: float = 1.0, tint_a: float = 1.0) -> None: ...
    def set_window_font_scale(self, scale: float) -> None: ...
    def draw_text(self, x: float, y: float, text: str, r: float, g: float, b: float, a: float, font_size: float = 0.0) -> None: ...
    def draw_text_aligned(self, min_x: float, min_y: float, max_x: float, max_y: float, text: str, r: float, g: float, b: float, a: float, align_x: float = 0.0, align_y: float = 0.0, font_size: float = 0.0, clip: bool = False) -> None: ...
    def calc_text_size(self, text: str, font_size: float = 0.0) -> tuple[float, float]: ...
    def push_draw_list_clip_rect(self, min_x: float, min_y: float, max_x: float, max_y: float, intersect_with_current: bool = True) -> None: ...
    def pop_draw_list_clip_rect(self) -> None: ...

    # Keyboard input
    def is_key_down(self, key_code: int) -> bool: ...
    def is_key_pressed(self, key_code: int) -> bool: ...
    def is_key_released(self, key_code: int) -> bool: ...

    # Focus
    def is_window_focused(self, flags: int = 0) -> bool: ...
    def is_window_hovered(self, flags: int = 0) -> bool: ...
    def capture_mouse_from_app(self, capture: bool) -> None: ...
    def capture_keyboard_from_app(self, capture: bool) -> None: ...


class InfGUIRenderable:
    """Base class for ImGui renderables — override on_render(ctx)."""

    def __init__(self) -> None: ...
    def on_render(self, ctx: InfGUIContext) -> None:
        """Called every frame to render ImGui widgets."""
        ...


class ResourcePreviewManager:
    """Manages resource previewers for Inspector."""

    def has_previewer(self, extension: str) -> bool: ...
    def get_previewer_type_name(self, extension: str) -> str: ...
    def get_all_supported_extensions(self) -> List[str]: ...
    def load_preview(self, file_path: str) -> None: ...
    def render_preview(
        self, ctx: InfGUIContext, avail_width: float, avail_height: float
    ) -> None: ...
    def render_metadata(self, ctx: InfGUIContext) -> None: ...
    def unload_preview(self) -> None: ...
    def is_preview_loaded(self) -> bool: ...
    def get_loaded_path(self) -> str: ...
    def get_current_type_name(self) -> str: ...


# =============================================================================
# InfEngine (main engine facade)
# =============================================================================


class InfEngine:
    """Main engine facade — Vulkan renderer, scene management, editor integration."""

    def __init__(self, dll_path: str) -> None: ...
    def init_renderer(self, width: int, height: int, project_path: str) -> None: ...
    def set_gui_font(self, font_path: str, font_size: float = 18.0) -> None: ...
    def run(self) -> None: ...
    def set_log_level(self, level: LogLevel) -> None: ...
    def register_gui_renderable(
        self, name: str, renderable: InfGUIRenderable
    ) -> None: ...
    def unregister_gui_renderable(self, name: str) -> None: ...
    def exit(self) -> None:
        """Exit the InfEngine application."""
        ...
    def is_close_requested(self) -> bool:
        """True when the user clicked the window close button but Python has not yet confirmed."""
        ...
    def confirm_close(self) -> None:
        """Actually close the engine (call after save dialogs are handled)."""
        ...
    def cancel_close(self) -> None:
        """Cancel a pending close request (user chose Cancel in save dialog)."""
        ...
    def show(self) -> None:
        """Show the InfEngine window."""
        ...
    def hide(self) -> None:
        """Hide the InfEngine window."""
        ...
    def modify_resources(self, file_path: str) -> None: ...
    def delete_resources(self, file_path: str) -> None: ...
    def move_resources(self, old_file_path: str, new_file_path: str) -> None: ...
    def reload_shader(self, shader_path: str) -> None:
        """Reload a shader file and refresh materials using it."""
        ...
    def get_file_manager(self) -> FileManager:
        """Get the file manager instance."""
        ...
    def get_asset_database(self) -> AssetDatabase:
        """Get the asset database instance."""
        ...
    def upload_texture_for_imgui(
        self, name: str, pixels: List[int], width: int, height: int
    ) -> int:
        """Upload texture data for ImGui display, returns texture ID."""
        ...
    def remove_imgui_texture(self, name: str) -> None:
        """Remove a previously uploaded ImGui texture."""
        ...
    def has_imgui_texture(self, name: str) -> bool:
        """Check if an ImGui texture exists."""
        ...
    def get_imgui_texture_id(self, name: str) -> int:
        """Get texture ID for an uploaded texture."""
        ...
    def get_resource_preview_manager(self) -> ResourcePreviewManager:
        """Get the resource preview manager."""
        ...

    # Scene camera controls
    def process_scene_view_input(
        self,
        delta_time: float,
        right_mouse_down: bool,
        middle_mouse_down: bool,
        mouse_delta_x: float,
        mouse_delta_y: float,
        scroll_delta: float,
        key_w: bool,
        key_a: bool,
        key_s: bool,
        key_d: bool,
        key_q: bool,
        key_e: bool,
        key_shift: bool,
    ) -> None:
        """Process scene view input for editor camera control."""
        ...
    def get_editor_camera_position(self) -> Tuple[float, float, float]:
        """Get editor camera position as (x, y, z) tuple."""
        ...
    def get_editor_camera_rotation(self) -> Tuple[float, float]:
        """Get editor camera rotation as (yaw, pitch) tuple."""
        ...
    def reset_editor_camera(self) -> None:
        """Reset editor camera to default position."""
        ...
    def focus_editor_camera_on(
        self, x: float, y: float, z: float, distance: float = 10.0
    ) -> None:
        """Focus editor camera on a point."""
        ...
    def get_editor_camera_focus_point(self) -> Tuple[float, float, float]:
        """Get editor camera focus point as (x, y, z) tuple."""
        ...
    def get_editor_camera_focus_distance(self) -> float:
        """Get editor camera focus distance."""
        ...
    def restore_editor_camera_state(
        self,
        pos_x: float, pos_y: float, pos_z: float,
        focus_x: float, focus_y: float, focus_z: float,
        focus_dist: float, yaw: float, pitch: float,
    ) -> None:
        """Restore full editor camera state."""
        ...
    def get_editor_camera_fov(self) -> float: ...
    def set_editor_camera_fov(self, fov: float) -> None: ...
    def get_editor_camera_near_clip(self) -> float: ...
    def set_editor_camera_near_clip(self, near_clip: float) -> None: ...
    def get_editor_camera_far_clip(self) -> float: ...
    def set_editor_camera_far_clip(self, far_clip: float) -> None: ...
    def editor_world_to_screen_point(self, x: float, y: float, z: float) -> Tuple[float, float]: ...

    # Scene render target
    def get_scene_texture_id(self) -> int:
        """Get scene render target texture ID for ImGui display."""
        ...
    def resize_scene_render_target(self, width: int, height: int) -> None:
        """Resize the scene render target."""
        ...

    # UI batch (Phase 0)
    def submit_ui_batch(self, vertices: List[float], indices: List[int], pass_target: int = 0, sort_order: int = 0) -> None:
        """Submit a UI batch with vertex stride 9: [x,y,u,v,r,g,b,a,tex_id]."""
        ...
    def clear_ui_batches(self) -> None:
        """Clear all queued UI batches."""
        ...
    def render_submitted_ui_batches(self, ctx: InfGUIContext, viewport_origin_x: float, viewport_origin_y: float, viewport_width: float, viewport_height: float) -> bool:
        """Render queued UI batches into current ImGui window draw list."""
        ...

    # Scene picking
    def pick_scene_object_id(
        self,
        screen_x: float,
        screen_y: float,
        viewport_width: float,
        viewport_height: float,
    ) -> int:
        """Pick a scene object by screen-space coordinates (0 if none)."""
        ...
    def pick_scene_object_ids(
        self,
        screen_x: float,
        screen_y: float,
        viewport_width: float,
        viewport_height: float,
    ) -> list[int]:
        """Pick ordered scene object candidate IDs by screen-space coordinates."""
        ...

    # Editor tools (gizmo highlight + ray)
    def set_editor_tool_highlight(self, axis: int) -> None:
        """Set highlighted gizmo axis. 0=None, 1=X, 2=Y, 3=Z."""
        ...
    def screen_to_world_ray(
        self,
        screen_x: float,
        screen_y: float,
        viewport_width: float,
        viewport_height: float,
    ) -> tuple[float, float, float, float, float, float]:
        """Build a world-space ray. Returns (ox,oy,oz, dx,dy,dz)."""
        ...

    # Editor gizmos
    def set_show_grid(self, show: bool) -> None: ...
    def is_show_grid(self) -> bool: ...
    def set_selection_outline(self, object_id: int) -> None:
        """Set selection outline for a game object. Pass 0 to clear."""
        ...
    def get_selected_object_id(self) -> int:
        """Get the currently selected object ID (0 if none)."""
        ...
    def clear_selection_outline(self) -> None: ...

    # Material pipeline
    def refresh_material_pipeline(self, material: InfMaterial) -> None:
        """Refresh a material's rendering pipeline."""
        ...

    # Render pipeline (SRP)
    def set_render_pipeline(
        self, pipeline: Optional[RenderPipelineCallback]
    ) -> None:
        """Set a custom RenderPipelineCallback. Pass None for default."""
        ...

    # Render graph access
    def get_scene_render_graph(self) -> SceneRenderGraph:
        """Get the scene render graph."""
        ...
    def get_readable_pass_names(self) -> List[str]:
        """Get render pass names with readback enabled."""
        ...
    def read_pass_color_pixels(
        self, pass_name: str
    ) -> Optional[npt.NDArray[np.uint8]]:
        """Read color pixels as NumPy array (height, width, 4) RGBA uint8."""
        ...
    def read_pass_depth_pixels(
        self, pass_name: str
    ) -> Optional[npt.NDArray[np.float32]]:
        """Read depth pixels as NumPy array (height, width) float32."""
        ...
    def get_pass_output_size(self, pass_name: str) -> Tuple[int, int]:
        """Get render pass output dimensions as (width, height)."""
        ...
    def get_pass_texture_id(self, pass_name: str) -> int:
        """Get render pass output texture ID for ImGui display."""
        ...

    # MSAA configuration
    def set_msaa_samples(self, samples: int) -> None:
        """Set MSAA sample count (1=off, 2, 4, 8) for both scene and game render targets."""
        ...
    def get_msaa_samples(self) -> int:
        """Get current MSAA sample count (1=off)."""
        ...


# =============================================================================
# InputManager — Unity-style input state manager
# =============================================================================


class InputManager:
    """
    Low-level input state manager (singleton).

    Use the Python ``Input`` class from ``InfEngine.input`` for the public API.
    This class exposes the raw C++ InputManager for direct access.
    """

    @staticmethod
    def instance() -> InputManager:
        """Get the singleton InputManager instance."""
        ...

    # ---- Keyboard ----
    def get_key(self, scancode: int) -> bool:
        """True while the key (by SDL scancode) is held down."""
        ...
    def get_key_down(self, scancode: int) -> bool:
        """True during the frame the key was pressed."""
        ...
    def get_key_up(self, scancode: int) -> bool:
        """True during the frame the key was released."""
        ...
    def any_key(self) -> bool:
        """True if any key is currently held down."""
        ...
    def any_key_down(self) -> bool:
        """True during the frame any key was first pressed."""
        ...

    # ---- Mouse buttons ----
    def get_mouse_button(self, button: int) -> bool:
        """True while mouse button is held (0=left, 1=right, 2=middle)."""
        ...
    def get_mouse_button_down(self, button: int) -> bool:
        """True during the frame the mouse button was pressed."""
        ...
    def get_mouse_button_up(self, button: int) -> bool:
        """True during the frame the mouse button was released."""
        ...

    # ---- Mouse position & delta (properties) ----
    @property
    def mouse_position_x(self) -> float:
        """Current mouse X (window-space pixels)."""
        ...
    @property
    def mouse_position_y(self) -> float:
        """Current mouse Y (window-space pixels)."""
        ...
    @property
    def mouse_delta_x(self) -> float:
        """Mouse X movement this frame."""
        ...
    @property
    def mouse_delta_y(self) -> float:
        """Mouse Y movement this frame."""
        ...

    # ---- Scroll wheel (properties) ----
    @property
    def mouse_scroll_delta_y(self) -> float:
        """Vertical scroll delta (positive = up)."""
        ...
    @property
    def mouse_scroll_delta_x(self) -> float:
        """Horizontal scroll delta."""
        ...

    # ---- Text input ----
    @property
    def input_string(self) -> str:
        """Characters typed this frame (UTF-8)."""
        ...

    # ---- Touch ----
    @property
    def touch_count(self) -> int:
        """Number of active touch contacts."""
        ...

    # ---- Utility ----
    def reset_all(self) -> None:
        """Clear all input state."""
        ...
    @staticmethod
    def name_to_scancode(name: str) -> int:
        """Map key name to SDL scancode. Returns -1 if unknown."""
        ...
    @staticmethod
    def scancode_to_name(scancode: int) -> str:
        """Get human-readable name for a scancode."""
        ...
