"""Type stubs for AssetManager."""

from typing import Any, List, Optional, Type


class AssetManager:
    @classmethod
    def initialize(cls, engine: Any) -> None: ...
    @classmethod
    def load(cls, path: str, asset_type: Optional[Type] = None) -> Optional[Any]: ...
    @classmethod
    def load_by_guid(cls, guid: str, asset_type: Optional[Type] = None) -> Optional[Any]: ...
    @classmethod
    def find_assets(cls, pattern: str, asset_type: Optional[Type] = None) -> List[str]: ...
    @classmethod
    def invalidate(cls, guid: str) -> None: ...
    @classmethod
    def invalidate_path(cls, path: str) -> None: ...
    @classmethod
    def flush(cls) -> None: ...
