"""Type stubs for InfEngine.core.material."""

from __future__ import annotations

from typing import Optional, Tuple

from InfEngine.lib._InfEngine import InfMaterial


class Material:
    """Pythonic wrapper around C++ InfMaterial.

    Provides context manager support, clean property setters/getters,
    and factory methods matching Unity's Material API.

    Example::

        mat = Material.create_lit("MyPBR")
        mat.set_color("_BaseColor", 1.0, 0.5, 0.0)
        mat.set_float("_Metallic", 0.9)

        with Material.create_lit("Temp") as mat:
            mat.set_float("_Roughness", 0.5)
    """

    def __init__(self, native: InfMaterial) -> None: ...

    # Factory methods
    @staticmethod
    def create_lit(name: str = ...) -> Material:
        """Create a new PBR lit material."""
        ...
    @staticmethod
    def create_unlit(name: str = ...) -> Material:
        """Create a new unlit material."""
        ...
    @staticmethod
    def from_native(native: InfMaterial) -> Material:
        """Wrap an existing C++ InfMaterial."""
        ...
    @staticmethod
    def load(file_path: str) -> Optional[Material]:
        """Load a material from a ``.mat`` file."""
        ...
    @staticmethod
    def get(name: str) -> Optional[Material]:
        """Look up a material by name in the global MaterialManager."""
        ...

    # Context manager
    def __enter__(self) -> Material: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...
    def dispose(self) -> None:
        """Release this material from the MaterialManager."""
        ...

    # Properties
    @property
    def native(self) -> InfMaterial: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def guid(self) -> str: ...
    @property
    def render_queue(self) -> int: ...
    @render_queue.setter
    def render_queue(self, value: int) -> None: ...
    @property
    def vertex_shader_path(self) -> str: ...
    @vertex_shader_path.setter
    def vertex_shader_path(self, path: str) -> None: ...
    @property
    def fragment_shader_path(self) -> str: ...
    @fragment_shader_path.setter
    def fragment_shader_path(self, path: str) -> None: ...
    @property
    def is_builtin(self) -> bool: ...

    # Shader property setters
    def set_float(self, name: str, value: float) -> None: ...
    def set_int(self, name: str, value: int) -> None: ...
    def set_color(self, name: str, r: float, g: float, b: float, a: float = ...) -> None: ...
    def set_vector2(self, name: str, x: float, y: float) -> None: ...
    def set_vector3(self, name: str, x: float, y: float, z: float) -> None: ...
    def set_vector4(self, name: str, x: float, y: float, z: float, w: float) -> None: ...
    def set_texture(self, name: str, texture_path: str) -> None: ...

    # Shader property getters
    def get_float(self, name: str, default: float = ...) -> float: ...
    def get_int(self, name: str, default: int = ...) -> int: ...
    def get_color(self, name: str) -> Tuple[float, float, float, float]: ...
    def get_vector3(self, name: str) -> Tuple[float, float, float]: ...
    def get_texture(self, name: str) -> Optional[str]: ...

    # Serialization
    def to_dict(self) -> dict: ...
    def save(self, file_path: str) -> bool:
        """Save material to a ``.mat`` file."""
        ...

    # Registration
    def register(self, engine: Optional[object] = ...) -> bool:
        """Register this material with the global MaterialManager."""
        ...

    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
