#pragma once

#include "InfFileLoader/InfFileLoader.h"
#include "InfResource/InfResource.h"
#include "InfResource/InfResourceMeta.h"
#include <core/types/InfFwdType.h>
#include <function/renderer/InfRenderer.h>

#include <algorithm>
#include <filesystem>
#include <unordered_map>
#include <unordered_set>

namespace infengine
{
class InfFileManager
{
  public:
    InfFileManager();
    ~InfFileManager() = default;

    // Disable copy (due to unique_ptr members)
    InfFileManager(const InfFileManager &) = delete;
    InfFileManager &operator=(const InfFileManager &) = delete;

    // Allow move
    InfFileManager(InfFileManager &&) = default;
    InfFileManager &operator=(InfFileManager &&) = default;

    /// @brief Remove resource meta by UID
    /// @param uid The unique identifier of the resource meta.
    void RemoveResourceMeta(const std::string &uid);

    /// @brief Unified file reading method with automatic binary detection.
    /// Use this instead of the removed legacy GetFileContent / GetFileContentBinary.
    /// @param filePath Path to the file
    /// @param content Vector to store file content
    /// @return true if successful, false otherwise
    bool ReadFile(const std::string &filePath, std::vector<char> &content) const;

    /// @brief Befor a file can be loaded, it must be registered with the file manager.
    /// @param filePath The path to the resource file.
    /// @param type The type of the resource (e.g., "Shader").
    /// @return the uid of the registered resource.
    std::string RegisterResource(const std::string &filePath, ResourceType type);

    /// @brief Load a resource by its UID. This is the only way to load a resource(for solve the problem of multiple
    /// resources with the same name).
    /// @param uid The unique identifier of the resource.
    /// @note The UID is generated by the RegisterResource method.
    /// @note The resource must be registered before it can be loaded.
    void LoadResource(const std::string &uid);

    /// @brief Unload a resource by its UID.
    /// @param uid The unique identifier of the resource.
    void UnloadResource(const std::string &uid);

    /// @brief load necessary shaders
    /// @param dir The directory containing the shader files.
    /// @param renderer The renderer instance used to load the shaders.
    void LoadDefaultShaders(const std::filesystem::path &dir, InfRenderer *renderer);

    /// @brief load all assets in ./Assets folder.
    /// @param dir The directory containing the asset files.
    void LoadAllAssets(const std::filesystem::path &dir);

    /// @brief Load shaders from Assets directory and compile them to renderer
    /// @param dir The Assets directory
    /// @param renderer The renderer instance used to load the shaders.
    void LoadAssetShaders(const std::filesystem::path &dir, InfRenderer *renderer);

    /// @brief Move/rename a resource file, preserving its GUID
    /// @param oldFilePath The old file path
    /// @param newFilePath The new file path
    void MoveResource(const std::string &oldFilePath, const std::string &newFilePath);

    /// @brief Delete a resource and its meta file
    /// @param filePath The file path to delete
    void DeleteResource(const std::string &filePath);

    /// @brief Notify that a resource has been modified, update meta
    /// @param filePath The modified file path
    void ModifyResource(const std::string &filePath);

    /// @brief Get metadata for a resource by its GUID
    /// @param guid The GUID of the resource
    /// @return Pointer to metadata or nullptr if not found
    const InfResourceMeta *GetMetaByGuid(const std::string &guid) const;

    /// @brief Get metadata for a resource by its file path
    /// @param filePath The file path
    /// @return Pointer to metadata or nullptr if not found
    const InfResourceMeta *GetMetaByPath(const std::string &filePath) const;

    /// @brief Get all registered resource GUIDs
    /// @return Vector of GUIDs
    std::vector<std::string> GetAllResourceGuids() const;

    /// @brief Get a loaded resource by its UID
    /// @param uid The unique identifier of the resource
    /// @return Pointer to the resource, or nullptr if not found
    const InfResource *GetResource(const std::string &uid) const;

    /// @brief Find shader file path by shader_id
    /// @param shaderId The shader_id to search for
    /// @param shaderType "vertex" or "fragment" (or extension ".vert", ".frag")
    /// @return File path of the shader, or empty string if not found
    std::string FindShaderPathById(const std::string &shaderId, const std::string &shaderType) const;

    /// @brief Get resources' type by it's extension name
    /// @param extensionName The extension name of the file (e.g., ".png", ".jpg"). get this from
    /// fs::path.extension().string().
    /// @return The ResourceType corresponding to the extension name. If not found, returns default text or binary.
    ResourceType GetResourcesType(const std::string &extensionName) const;

    /// @brief Get resource type from a file path
    /// @param filePath Path to the file
    /// @return The ResourceType for the file
    ResourceType GetResourceTypeForPath(const std::string &filePath) const;

  private:
    /// @brief Determine if a file is binary based on extension and content
    /// @param filePath Path to the file
    /// @return true if binary, false if text
    bool IsBinaryFile(const std::string &filePath) const;

    /// @brief Detect binary file by examining file content
    /// @param filePath Path to the file
    /// @return true if binary, false if text
    bool DetectBinaryByContent(const std::string &filePath) const;

    /// @brief Read file content into vector<char>
    /// @param filePath Path to the file
    /// @param content Vector to store file content
    /// @param binary Whether to open file in binary mode
    /// @return true if successful, false otherwise
    bool ReadFileToContainer(const std::string &filePath, std::vector<char> &content, bool binary) const;

    std::unordered_map<ResourceType, std::unique_ptr<InfFileLoader>> m_loaders_umap;
    std::unordered_map<std::string, std::unique_ptr<InfResourceMeta>> m_metas_umap;
    std::unordered_map<std::string, std::unique_ptr<InfResource>> m_resources_umap;
    std::unordered_map<std::string, std::string> m_pathToGuid; // file_path → guid reverse index
};
} // namespace infengine